/**
 * Downloads the app's typefaces once and stores them under assets/fonts so the
 * app renders identically with no network. Run again only to change the faces.
 *
 * Google Fonts CSS API is used as a *download* source. The app itself never
 * references fonts.googleapis.com — only local woff2 via assets/css/fonts.css.
 */
import { mkdir, writeFile, readdir, unlink } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "assets", "fonts");
const CSS_OUT = path.join(ROOT, "assets", "css", "fonts.css");

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36";

/** Google Fonts faces — one woff2 per (family, axis, subset, unicode-range slice). */
const GOOGLE_FACES = [
  { family: "Amiri", axis: "wght@400;700", slug: "amiri", subsets: ["arabic"] },
  { family: "Noto Naskh Arabic", axis: "wght@400..700", slug: "noto-naskh-arabic", subsets: ["arabic"] },
  { family: "Playfair Display", axis: "wght@400..800", slug: "playfair-display", subsets: ["latin", "latin-ext"] }
];

async function fetchText(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.text();
}

function parseFaces(css) {
  const blocks = css.split("@font-face").slice(1);
  return blocks.map((block) => ({
    family: /font-family:\s*'([^']+)'/.exec(block)?.[1] ?? "",
    style: /font-style:\s*([^;]+)/.exec(block)?.[1]?.trim() ?? "normal",
    weight: /font-weight:\s*([^;]+)/.exec(block)?.[1]?.trim() ?? "400",
    range: /unicode-range:\s*([^;]+)/.exec(block)?.[1]?.trim() ?? "",
    url: /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1] ?? ""
  }));
}

function faceRule({ family, style, weight, file, range }) {
  return [
    "@font-face {",
    `  font-family: '${family}';`,
    `  font-style: ${style};`,
    `  font-weight: ${weight};`,
    "  font-display: swap;",
    `  src: url('../fonts/${file}') format('woff2');`,
    range ? `  unicode-range: ${range};` : null,
    "}"
  ]
    .filter(Boolean)
    .join("\n");
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const used = new Set();
  const rules = [];

  for (const face of GOOGLE_FACES) {
    for (const subset of face.subsets) {
      const query = `family=${face.family.replace(/ /g, "+")}:${face.axis}&display=swap&subset=${subset}`;
      const css = await fetchText(`https://fonts.googleapis.com/css2?${query}`);
      const parsed = parseFaces(css).filter((entry) => {
        if (!entry.url) return false;
        if (face.family === "Amiri" || face.family === "Noto Naskh Arabic") {
          return /U\+0600/i.test(entry.range);
        }
        return true;
      });
      let index = 0;
      for (const entry of parsed) {
        const name = `${face.slug}-${subset}-${index}.woff2`;
        const dest = path.join(OUT, name);
        if (!existsSync(dest)) {
          const res = await fetch(entry.url, { headers: { "User-Agent": UA } });
          if (!res.ok) throw new Error(`${res.status} ${entry.url}`);
          await writeFile(dest, Buffer.from(await res.arrayBuffer()));
        }
        used.add(name);
        rules.push(
          faceRule({
            family: entry.family,
            style: entry.style,
            weight: entry.weight,
            file: name,
            range: entry.range
          })
        );
        index += 1;
      }
      console.log(`fonts: ${face.family} (${subset}) — ${parsed.length} files`);
    }
  }

  const header = "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n";
  await writeFile(CSS_OUT, `${header}\n${rules.join("\n\n")}\n`, "utf8");
  console.log(`fonts: wrote assets/css/fonts.css (${rules.length} faces)`);

  const kept = [];
  for (const file of await readdir(OUT)) {
    if (!file.endsWith(".woff2")) continue;
    if (used.has(file)) {
      kept.push(file);
      continue;
    }
    await unlink(path.join(OUT, file));
    console.log(`fonts: removed stale ${file}`);
  }
  console.log(`fonts: ${kept.length} files kept`);
}

main().catch((error) => {
  console.error("fetch-fonts failed:", error.message);
  process.exit(1);
});
